[all:vars]

[routers]
asr1 ansible_host=172.21.56.121
asr2 ansible_host=172.21.56.122

[routers:vars]
ansible_user=cisco
ansible_password=cisco
ansible_network_os=ios
ntp_server1="192.0.2.1"
ntp_server2="192.0.2.2"